---
name: Update Doc Version

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  readme-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHANGESETS_TOKEN }}

      # we use ourself to get the information for the release
      - name: Get Change Info
        uses: ./
        id: get-changelog-info

      - name: Update Version In Files
        shell: bash
        # yamllint disable rule:line-length
        run: |
          latest_version="${{ steps.get-changelog-info.outputs.last-change-version }}"
          files="README.md"

          # replace the version "latest-v0.0.4-blue" with the latest
          sed -i "s/latest-v.*-blue/latest-${latest_version}-blue/g" $files

          # update any doc references to ourself; chizmw/changesets-changelog-info@v0.0.4
          sed -i "s/chizmw\/changesets-changelog-info@v.*/chizmw\/changesets-changelog-info@${latest_version}/g" $files

          # commit and push the changes
          git config --global --add --bool push.autoSetupRemote true
          git add $files
          git commit -m "chore: update version in files (${{ steps.get-changelog-info.outputs.last-change-version}})"
          git push
        # yamllint enable rule:line-length

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          # yamllint disable rule:line-length
          title: 'chore: update version in files (${{ steps.get-changelog-info.outputs.last-change-version}})'
          commit-message: 'chore: update version in files (${{ steps.get-changelog-info.outputs.last-change-version}})'
          delete-branch: true
          # yamllint enable rule:line-length
